language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t masashiu/multi-client:latest -f Dockerfile.dev ./client

script:
  - docker run -e CI=true masashiu/react-test npm test

after_success:
  - docker build -t masashiu/multi-client:latest ./client
  - docker build -t masashiu/multi-nginx:latest ./nginx
  - docker build -t masashiu/multi-server:latest ./server
  - docker build -t masashiu/multi-worker:latest ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push masashiu/multi-client:latest
  - docker push masashiu/multi-nginx:latest
  - docker push masashiu/multi-server:latest
  - docker push masashiu/multi-worker:latest

deploy:
  # edge: true  # if missing bucket_name error
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "uemura-udemy-k8s"
  env: "UemuraUdemyK8sMultiDocker-env"
  bucket_name: elasticbeanstalk-ap-northeast-1-085107194442
  bucket_path: "uemura-multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_KEY: $AWS_SECRET_KEY
