version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image : redis:latest

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      PGUSER: ${PGUSER}
      PGHOST: postgres
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
    depends_on:
      - postgres
    # stdin_open:
    #   true

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open:
      true

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - /app/node_modules
      - ./worker:/app
    # stdin_open:
    #   true
